server:
  port: 8080

spring:
  application:
    name: jedi-channel-service
  profiles:
    active: dev
jedi:
  track:
    redis:
      enabled: true
      host: 47.93.114.117
      port: 6379
      password: test001
      database: 3

