server:
  port: 8080

spring:
  application:
    #必须配置
    name: jedi-track
  profiles:
    active: dev
jedi:
  track:
    #开启追踪
    enabled: true
    #Redis配置
    redis:
      enabled: true
      host: 47.93.114.117
      port: 6379
      password: test001
      database: 3
    #持久化配置
    presistent:
      #文件持久化方式:com.huifenqi.jedi.track.presistent.FilePresistent
      #控制台打印 : com.huifenqi.jedi.track.presistent.PrintConsolePresistent
      className: com.huifenqi.jedi.track.presistent.PrintConsolePresistent
      #持久化为文件配置，默认/data/track
      path: /data/track


